import os
import sys
import json
import pytest
from unittest.mock import patch

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

def test_graph_implicit_edges(test_client, db):
    # Seed the DB with a single investment track and two companies to test edge auto-generation
    cursor = db.cursor()
    cursor.execute("INSERT INTO investment_tracks (id, name, description) VALUES (999, 'Test Track', 'Unit test track')")
    cursor.execute("INSERT INTO companies (id, ticker, name) VALUES (998, 'TEST_A', 'Test Company A')")
    cursor.execute("INSERT INTO companies (id, ticker, name) VALUES (999, 'TEST_B', 'Test Company B')")
    
    # Link them both to the same track
    cursor.execute("INSERT INTO company_tracks (track_id, company_id) VALUES (999, 998)")
    cursor.execute("INSERT INTO company_tracks (track_id, company_id) VALUES (999, 999)")
    db.commit()

    resp = test_client.get('/nexus/api/graph')
    assert resp.status_code == 200
    data = resp.json
    
    assert 'nodes' in data
    assert 'edges' in data

    # Verify both test nodes are returned
    nodes = {n['ticker']: n for n in data['nodes']}
    assert 'TEST_A' in nodes
    assert 'TEST_B' in nodes

    
    # We expect competitor edges generated implicitly between companies sharing the same track
    edges = data['edges']
    found_competitor = any(
        e['source'] in ('test_a', 'test_b') and
        e['target'] in ('test_a', 'test_b') and
        e['type'] == 'competitor'
        for e in edges
    )
    assert found_competitor, "Implicit competitor edges not generated by /graph for nodes in the same track."


def test_live_data_bypasses_cache(test_client):
    ticker = "FAKE_LIVE"
    fake_data = {
        "ticker": ticker,
        "price": 420.69,
        "marketCap": 1337000,
        "companyName": "Fake Live Data Corp",
        "previousClose": 400.0,
        "trailingPE": 42.0,
        "sector": "Testing",
        "industry": "Automated Testing"
    }

    # Patch yf.Ticker directly where it's used in main.py
    with patch('main.yf.Ticker') as MockTicker:
        # Mock the info dict
        mock_instance = MockTicker.return_value
        mock_instance.info = {
            "quoteType": "EQUITY",
            "longName": "Fake Live Data Corp",
            "currentPrice": 420.69,
            "sector": "Testing",
        }
        
        # Test the live proxy endpoint
        resp = test_client.get(f'/nexus/api/companies/{ticker}/live')
        
    assert resp.status_code == 200
    data = resp.json
    
    # Assert data surfaces straight from the mock, ignoring cache
    assert data['price'] == 420.69
    assert data['companyName'] == "Fake Live Data Corp"
    assert data['sector'] == "Testing"


def test_pipeline_integrity():
    # Verify all targets in the AI outputs are present in ticker_track.json to prevent edge breaking
    base_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
    ticker_track_path = os.path.join(base_dir, 'ticker_track.json')
    
    if not os.path.exists(ticker_track_path):
        pytest.skip("ticker_track.json not found, skipping integrity check")
        
    with open(ticker_track_path, 'r', encoding='utf-8') as f:
        master_tickers = json.load(f)
        
    task5_dir = os.path.join(base_dir, 'task5', 'SeleniumAI_Task5', 'final_json')
    
    if not os.path.exists(task5_dir):
        pytest.skip("task5 pipeline output directory not found, skipping integrity check")
        
    for fname in os.listdir(task5_dir):
        if fname.endswith('.json'):
            file_path = os.path.join(task5_dir, fname)
            with open(file_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
            
            # The schema states "related_stocks": [{"ticker": "MSFT", ...}]
            for rel in data.get('related_stocks', []):
                target = rel.get('ticker') or rel.get('target_ticker')
                if target:
                    target = target.strip()
                    assert target in master_tickers, f"Pipeline Error: Relationship target {target} in {fname} is missing from the master ticker_track.json dictionary."
